sonar.projectKey=bajaj-python
sonar.projectName=Bajaj Python App
sonar.sources=.
sonar.tests=tests
sonar.exclusions=venv/**,__pycache__/**,tests/**,.github/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.sourceEncoding=UTF-8
